apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prompt-ads-sql-secret
  namespace: promptsales
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
  target:
    name: prompt-ads-sql
    creationPolicy: Owner
  data:
    - secretKey: connectionString
      remoteRef:
        key: promptsales/sql/ads
        property: connectionString
