apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-credentials
  namespace: promptsales
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: auth0-secret            # nombre del Secret Kubernetes resultante
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: auth0/production     # ruta en AWS Secrets Manager
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: auth0/production
        property: client-secret
