apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prompt-content-mongo-secret
  namespace: promptsales
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
  target:
    name: prompt-content-mongo
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: promptsales/mongo/production
        property: uri
