apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_ME_AWS_REGION
      auth:
        # usa IRSA: referenciar el ServiceAccount creado
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
