apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # IAM role ARN que permitirá leer AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ME_AWS_ACCOUNT:role/ExternalSecretsAccessRole

    # REPLACE_ME: crea en AWS un IAM Role ExternalSecretsAccessRole con una trust policy para el
    # OIDC provider del cluster (o usa IRSA). Esa role necesita permisos secretsmanager:GetSecretValue, 
    # secretsmanager:DescribeSecret (y kms:Decrypt si usáis CMKs).
