# k8s/eks/etcd-encryption.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
  - secrets
  providers:
  - kms:
      name: awskms
      endpoint: unix:///var/run/kmsplugin/socket.sock
  - identity: {}